name: Hexo Deploy

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: source

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "disappear9@outlook.com"
          git config --global user.name "Disappear9"
          npm install hexo-cli -g
          npm install
          git submodule update --init --recursive
          rm themes/yilia/_config.yml
          chmod +x deploy.sh

      - name: Deploy
        run: |
          hexo g
          ./deploy.sh
